### ISSUE TITLE
Ensure that the output of `create` does not contain long lines

### ISSUE THREAD

**Issue by vil02** [vil02/puzzle_generator#111]
The output of [`create`](https://github.com/vil02/puzzle_generator/blob/32e2102f144ed1748ce7df17b0e72c92efb6ae6c/puzzle_generator/create_puzzle.py#L54) contains some very long lines. Modify the code in such a way, that each line of the output is at most [88](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length) characters long.

## How to see the problem
Generate and inspect any puzzle, for example by running
```shell
poetry run python3 examples/basic_usage.py > example_output.py
```
and opening the generated `example_output.py` file.

## Testing strategy
Adding a line like
```python3
assert all(len(_) <= 88 for _ in in_puzzle.splitlines())
```
into [`_run_puzzle_str`](https://github.com/vil02/puzzle_generator/blob/32e2102f144ed1748ce7df17b0e72c92efb6ae6c/tests/test_create_puzzle.py#L105) is a good start.

**Comment by mpa-LHutchinson** [comment]
Hi @vil02 , can you assign this issue to me? I'll get working on it as soon as I can today

**Comment by vil02** [comment]
@mpa-LHutchinson: if you would like to discuss something more directly, feel free to e-mail me: vil02_puzzle_generator@10g.pl.

**Comment by vil02** [comment]
@mpa-LHutchinson: do you need some support?

**Comment by mpa-LHutchinson** [comment]
Hi @vil02, I've been busy as of late and I don't think I'll be able to work on this issue. If you want you can assign it to someone else. Sorry for not letting you know sooner.

**Comment by vil02** [comment]
@mpa-LHutchinson: no worries. Thanks for an update.
