### ISSUE TITLE
Remove `_split_long_str` and use `textwrap.wrap` instead

### ISSUE THREAD

**Issue by vil02** [vil02/puzzle_generator#150]
Replace

https://github.com/vil02/puzzle_generator/blob/7f612b3110470f2d9880ed37966fd96cfeeb406d/puzzle_generator/create_puzzle.py#L23

by [`textwrap.wrap`](https://docs.python.org/3/library/textwrap.html#textwrap.wrap).

**Comment by zhaohany** [comment]
Hi @vil02 , I raised a PR for this: https://github.com/vil02/puzzle_generator/pull/151
Thank you.
