### ISSUE TITLE
Remove `assert`s from `bytes_utils.int_to_bytes`

### ISSUE THREAD

**Issue by vil02** [vil02/puzzle_generator#62]
The `assert`s in [`bytes_utils.int_to_bytes`](https://github.com/vil02/puzzle_generator/blob/227703e928d7e1ae855dd0f95f88cd8e07c331f1/puzzle_generator/bytes_utils.py#L7) should be removed. What needs to be done:

- proper exception should be raised if the input is negative or does not fit into 256 bytes,
- function `byte_length` should be introduced.

**Comment by muddi900** [comment]
Hi, I am working on this issue.

What is this line testing for?

```
assert (
        number_of_bytes - 1 <= in_value.bit_length() // 8 <= number_of_bytes
    )  # nosec B101
```

**Comment by vil02** [comment]
> Hi, I am working on this issue.
> 
> What is this line testing for?
> 
> ```
> assert (
>         number_of_bytes - 1 <= in_value.bit_length() // 8 <= number_of_bytes
>     )  # nosec B101
> ```

Good question. I think I just wanted to convince myself, that the `number_of_bytes` is _optimal_ (i.e. it is not _one too big_).

It can be removed, when the new function `byte_length` will be properly tested.
